# Generated by Django 5.1.4 on 2025-11-24 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(choices=[(True, 'Paid'), (False, 'Purchased')], default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the credit')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='customers.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
