# Generated by Django 5.1.4 on 2025-11-24 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(blank=True, help_text='If this is an assembly product (Bill of Materials)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_session_items', to='inventory.productassembly')),
                ('inventory', models.ForeignKey(blank=True, help_text='Regular inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_session_items', to='inventory.inventory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_items', to='billing.billingsession')),
            ],
        ),
    ]
